### ISSUE TITLE
Allow bulk scoring of Questions based on Tags

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#85]
Have a way by which we could view a list of Qs with their scores, searched by tags, and then bulk edit their scoring.

**Comment by pawanrawal** [comment]
I am thinking that instead of this how about automating the score calculation process according to the tags? 
So we can have two options, one would be to enter score manually, second would be to calculate it using the tags. Of course, we'd need a page to input the multiplication factors for different tags and a way to calculate the scores.
